services:
  be2:
    build:
      context: ./be2
      dockerfile: Dockerfile
    image: ghcr.io/giakiet05/test-homeserver-be2:latest
    container_name: test-be2
    restart: unless-stopped
    environment:
      - PORT=4002
      - NODE_ENV=production

  be1:
    build:
      context: ./be1
      dockerfile: Dockerfile
    image: ghcr.io/giakiet05/test-homeserver-be1:latest
    container_name: test-be1
    restart: unless-stopped
    depends_on:
      - be2
    environment:
      - PORT=4001
      - BE2_URL=http://be2:4002
      - NODE_ENV=production

  fe:
    build:
      context: ./fe
      dockerfile: Dockerfile
    image: ghcr.io/giakiet05/test-homeserver-fe:latest
    container_name: test-fe
    restart: unless-stopped
    depends_on:
      - be1
    ports:
      - "8085:80"
